export * from './HomePage';
export * from './CatalogPage';
export * from './BasketPage';
export * from './CategoryPage';
export * from './FavoritesPage';
export * from './NotFoundPage';
export * from './ProductPage';
export * from './LoginPage';
export * from './RegisterPage';
